version: '3.8'

services:
  ai-town:
    build: .
    ports:
      - "5173:5173"
      - "3210:3210"  # WebSocket port ... In mysterious ways, this port make the magic happen !
    volumes:
      - ./.vscode:/usr/src/app/.vscode
      - ./assets:/usr/src/app/assets
      - ./convex:/usr/src/app/convex
      - ./data:/usr/src/app/data
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./README.md:/usr/src/app/README.md
      - convex_data:/usr/src/app/convex-local-storage
    networks:
      - ai-town-network

networks:
  ai-town-network:
    driver: bridge







volumes:
  convex_data:
